"""SOL membership checkout. No custody, signing, or transaction submission."""
from __future__ import annotations

from dataclasses import dataclass, replace
from contextlib import contextmanager
import os
import hashlib
from datetime import datetime, timedelta, timezone
import secrets
import sqlite3
import time
import re
from urllib.parse import urlencode

import requests
from fastapi import APIRouter, HTTPException, Request, Response
from pydantic import BaseModel, ConfigDict, Field

from .beta_config import BetaConfig
from .beta_auth import BETA_COOKIE, issue_session
from .security import FailedAttemptLimiter, client_key

ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
SYSTEM = "11111111111111111111111111111111"
GENESIS = {"mainnet-beta": "5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d", "devnet": "EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG"}


def b58encode(raw: bytes) -> str:
    n = int.from_bytes(raw, "big")
    result = ""
    while n:
        n, digit = divmod(n, 58)
        result = ALPHABET[digit] + result
    return "1" * (len(raw) - len(raw.lstrip(b"\0"))) + result


def b58decode(value: str) -> bytes:
    n = 0
    for char in value:
        n = n * 58 + ALPHABET.index(char)
    return b"\0" * (len(value) - len(value.lstrip("1"))) + n.to_bytes((n.bit_length() + 7) // 8, "big")


@dataclass(frozen=True)
class PaymentConfig:
    enabled: bool = False
    network: str = "devnet"
    recipient: str = ""
    price_lamports: int = 0
    days: int = 0
    credits: int = 0
    runs_daily: int = 1
    daily_credits: int = 0
    rpc_url: str = "https://api.devnet.solana.com"

    @classmethod
    def from_env(cls):
        network = os.getenv("JEET_SOL_NETWORK", "mainnet-beta")
        rpc_url = os.getenv("JEET_SOL_RPC_URL", "").strip()
        if not rpc_url:
            helius_key = os.getenv("HELIUS_API_KEY", "").strip()
            if helius_key and network in GENESIS:
                cluster = "mainnet" if network == "mainnet-beta" else "devnet"
                rpc_url = f"https://{cluster}.helius-rpc.com/?" + urlencode({"api-key": helius_key})
            else:
                rpc_url = "https://api.devnet.solana.com" if network == "devnet" else "https://api.mainnet-beta.solana.com"
        return cls(
            enabled=os.getenv("JEET_SOL_PAYMENTS_ENABLED", "0") == "1",
            network=network,
            recipient=os.getenv("JEET_SOL_RECIPIENT", ""),
            price_lamports=int(os.getenv("JEET_SOL_PRICE_LAMPORTS", "500000000")),
            days=int(os.getenv("JEET_SOL_MEMBERSHIP_DAYS", "30")),
            credits=int(os.getenv("JEET_SOL_MEMBER_CREDITS", "250000")),
            runs_daily=int(os.getenv("JEET_SOL_MEMBER_RUNS_DAILY", "0")),
            daily_credits=int(os.getenv("JEET_SOL_MEMBER_DAILY_CREDITS", "250000")),
            rpc_url=rpc_url,
        )

    def validate(self, beta):
        if not self.enabled:
            return
        if self.network not in GENESIS or not self.rpc_url.startswith("https://"):
            raise ValueError("Payments require an HTTPS RPC and supported Solana network")
        if len(b58decode(self.recipient)) != 32 or self.recipient == SYSTEM:
            raise ValueError("Configure a valid SOL receiving public address")
        if not 0 < self.price_lamports < 2**53 or not 1 <= self.days <= 366:
            raise ValueError("Configure a positive lamport price and 1-366 membership days")
        if not beta.max_estimated_credits_per_run < self.credits <= beta.global_daily_credit_cap or self.runs_daily < 0:
            raise ValueError("Paid credits must exceed free credits and fit the global daily cap")
        if self.daily_credits < 0 or self.daily_credits > beta.global_daily_credit_cap:
            raise ValueError("Daily member credits must fit the service-wide provider budget")
        if self.network == "mainnet-beta" and (not beta.public_origin or not beta.cookie_secure):
            raise ValueError("Mainnet checkout requires a public HTTPS origin and secure cookies")


def valid_transfer(tx, invoice, signature):
    """Verify a finalized raw RPC receipt, including instruction-bound reference."""
    try:
        meta = tx["meta"]
        if meta["err"] is not None or tx["transaction"]["signatures"][0] != signature:
            return False
        if not invoice["created"] <= tx["blockTime"] <= invoice["expires"]:
            return False
        message = tx["transaction"]["message"]
        keys = message["accountKeys"]
        # References generated by this checkout must be static, readonly, nonsigning.
        ref_index = keys.index(invoice["reference"])
        header = message["header"]
        if ref_index < header["numRequiredSignatures"] or ref_index < len(keys) - header["numReadonlyUnsignedAccounts"]:
            return False
        all_keys = keys + meta.get("loadedAddresses", {}).get("writable", []) + meta.get("loadedAddresses", {}).get("readonly", [])
        for instruction in message["instructions"]:
            if all_keys[instruction["programIdIndex"]] != SYSTEM:
                continue
            raw = b58decode(instruction["data"])
            accounts = instruction["accounts"]
            if len(raw) != 12 or int.from_bytes(raw[:4], "little") != 2 or len(accounts) < 3:
                continue
            source, destination = accounts[:2]
            if ref_index not in accounts[2:] or source >= header["numRequiredSignatures"]:
                continue
            if all_keys[destination] != invoice["recipient"] or source == destination:
                continue
            if int.from_bytes(raw[4:], "little") != invoice["lamports"]:
                continue
            if meta["postBalances"][destination] - meta["preBalances"][destination] < invoice["lamports"]:
                continue
            return True
    except (KeyError, TypeError, ValueError, IndexError, OverflowError):
        pass
    return False


class PaymentReplayError(HTTPException):
    """A shared verifier rejection that adapters can audit without parsing prose."""
    payment_state = 'replay_rejected'


class SolPayments:
    def __init__(self, beta: BetaConfig, config: PaymentConfig):
        config.validate(beta)
        self.beta, self.config = beta, config
        with self.connection() as db:
            db.executescript("""
                CREATE TABLE IF NOT EXISTS sol_invoices (
                  id TEXT PRIMARY KEY, code_id TEXT NOT NULL, reference TEXT UNIQUE NOT NULL,
                  recipient TEXT NOT NULL, lamports INTEGER NOT NULL, network TEXT NOT NULL,
                  days INTEGER NOT NULL, credits INTEGER NOT NULL, runs_daily INTEGER NOT NULL,
                  created INTEGER NOT NULL, expires INTEGER NOT NULL, last_check INTEGER NOT NULL DEFAULT 0,
                  signature TEXT UNIQUE, paid_at INTEGER);
                CREATE INDEX IF NOT EXISTS sol_invoice_owner ON sol_invoices(code_id,created);
                CREATE TABLE IF NOT EXISTS sol_memberships (
                  code_id TEXT PRIMARY KEY, expires INTEGER NOT NULL, credits INTEGER NOT NULL,
                  runs_daily INTEGER NOT NULL, network TEXT NOT NULL);
                CREATE TABLE IF NOT EXISTS sol_payment_audit (
                  id INTEGER PRIMARY KEY, invoice_id TEXT NOT NULL, event TEXT NOT NULL, at INTEGER NOT NULL);
                CREATE TABLE IF NOT EXISTS sol_recovery (
                  digest TEXT PRIMARY KEY, code_id TEXT UNIQUE NOT NULL);
            """)

        with self.connection() as db:
            for table in ("sol_invoices", "sol_memberships"):
                columns = {row[1] for row in db.execute(f"PRAGMA table_info({table})")}
                if "daily_credits" not in columns:
                    db.execute(f"ALTER TABLE {table} ADD COLUMN daily_credits INTEGER NOT NULL DEFAULT 0")

    @contextmanager
    def connection(self):
        db = sqlite3.connect(self.beta.database_path, timeout=10)
        db.row_factory = sqlite3.Row
        try:
            with db:
                yield db
        finally:
            db.close()

    def membership(self, code_id):
        with self.connection() as db:
            row = db.execute("SELECT * FROM sol_memberships WHERE code_id=? AND expires>? AND network=?", (code_id, int(time.time()), self.config.network)).fetchone()
        return dict(row) if row else None

    def effective_config(self, code_id):
        member = self.membership(code_id)
        if not member:
            return self.beta
        # Honour purchased terms even if new checkout is paused. Global cap remains enforced.
        if member["credits"] > self.beta.global_daily_credit_cap:
            raise HTTPException(503, "Member investigations are temporarily unavailable under the current provider budget")
        scale = lambda limit: max(limit, (limit * member["credits"] + self.beta.max_estimated_credits_per_run - 1) // self.beta.max_estimated_credits_per_run)
        return replace(self.beta, max_estimated_credits_per_run=member["credits"], max_runs_per_code_per_day=member["runs_daily"],
                       max_estimated_credits_per_code_per_day=member["daily_credits"] or None,
                       max_wallets=scale(self.beta.max_wallets), max_pages=scale(self.beta.max_pages),
                       max_rpc_requests=scale(self.beta.max_rpc_requests), max_signatures=scale(self.beta.max_signatures),
                       max_transactions=scale(self.beta.max_transactions))

    def daily_usage(self, code_id):
        member = self.membership(code_id)
        if not member or not member["daily_credits"]:
            return None
        day = datetime.now(timezone.utc).date()
        with self.connection() as db:
            used = db.execute("SELECT COALESCE(SUM(CASE WHEN state IN ('queued','running') THEN estimated_credits_reserved ELSE estimated_credits_used END),0) FROM beta_investigations WHERE code_id=? AND substr(created_at,1,10)=?", (code_id, day.isoformat())).fetchone()[0]
        return {"limit": member["daily_credits"], "committed": used, "remaining": max(0, member["daily_credits"]-used), "resets_at": (day+timedelta(days=1)).isoformat()+"T00:00:00Z"}

    def pending_invoice(self, code_id):
        with self.connection() as db:
            row = db.execute("SELECT * FROM sol_invoices WHERE code_id=? AND signature IS NULL AND network=? ORDER BY created DESC LIMIT 1", (code_id, self.config.network)).fetchone()
            return self.public_invoice(row) if row else None

    def recovery_code(self, code_id):
        raw = secrets.token_urlsafe(32)
        with self.connection() as db:
            db.execute("INSERT OR REPLACE INTO sol_recovery VALUES(?,?)", (hashlib.sha256(raw.encode()).hexdigest(), code_id))
        return raw

    def recover(self, raw):
        with self.connection() as db:
            row = db.execute("SELECT code_id FROM sol_recovery WHERE digest=?", (hashlib.sha256(raw.encode()).hexdigest(),)).fetchone()
        if not row:
            raise HTTPException(401, "Recovery code not recognized")
        code_id = row[0]
        if code_id not in self.beta.code_hashes and not (self.beta.public_access and code_id.startswith("visitor-") and len(code_id) == 40):
            raise HTTPException(401, "This access identity has been revoked")
        return code_id

    def public_invoice(self, row):
        value = dict(row)
        value.pop("code_id")
        amount = f'{value["lamports"] // 10**9}.{value["lamports"] % 10**9:09d}'
        value["amount_sol"] = amount
        # Devnet has no portable transfer-URI cluster selector; never launch it as mainnet.
        value["payment_url"] = ("solana:" + value["recipient"] + "?" + urlencode({"amount": amount, "reference": value["reference"], "label": "Jeet Analyzer membership"})) if value["network"] == "mainnet-beta" else None
        return value

    def invoice_for_owner(self, code_id, identifier):
        """Read a validated owned invoice; transports never query another account."""
        if not isinstance(identifier, str) or not re.fullmatch(r'[0-9a-f]{32}', identifier):
            raise HTTPException(422, 'Invalid payment session')
        with self.connection() as db:
            row = db.execute('SELECT * FROM sol_invoices WHERE id=? AND code_id=?', (identifier, code_id)).fetchone()
        if row is None:
            raise HTTPException(404, 'Invoice not found')
        return self.public_invoice(row)

    def create_invoice(self, code_id):
        c, now = self.config, int(time.time())
        if not c.enabled or not self.beta.enabled:
            raise HTTPException(503, "SOL checkout is not enabled")
        with self.connection() as db:
            db.execute("BEGIN IMMEDIATE")
            if db.execute("SELECT 1 FROM sol_memberships WHERE code_id=? AND expires>? AND network=?", (code_id, now, c.network)).fetchone():
                raise HTTPException(409, "Membership is already active; no additional payment is needed")
            pending = db.execute("SELECT * FROM sol_invoices WHERE code_id=? AND signature IS NULL AND expires>? AND network=? ORDER BY created DESC LIMIT 1", (code_id, now, c.network)).fetchone()
            if pending:
                return self.public_invoice(pending)
            if db.execute("SELECT COUNT(*) FROM sol_invoices WHERE code_id=? AND created>?", (code_id, now-86400)).fetchone()[0] >= 5:
                raise HTTPException(429, "Too many checkout requests; try later")
            identifier = secrets.token_hex(16)
            db.execute("INSERT INTO sol_invoices(id,code_id,reference,recipient,lamports,network,days,credits,runs_daily,created,expires,daily_credits) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)", (identifier, code_id, b58encode(secrets.token_bytes(32)), c.recipient, c.price_lamports, c.network, c.days, c.credits, c.runs_daily, now, now+86400, c.daily_credits))
            db.execute("INSERT INTO sol_payment_audit(invoice_id,event,at) VALUES(?,?,?)", (identifier, "created", now))
            return self.public_invoice(db.execute("SELECT * FROM sol_invoices WHERE id=?", (identifier,)).fetchone())

    def rpc(self, method, params):
        try:
            response = requests.post(self.config.rpc_url, json={"jsonrpc": "2.0", "id": 1, "method": method, "params": params}, timeout=15)
            response.raise_for_status()
            payload = response.json()
            if "error" in payload or "result" not in payload:
                raise ValueError("Invalid RPC response")
            return payload["result"]
        except (requests.RequestException, ValueError):
            raise HTTPException(503, "Payment verification is temporarily unavailable; do not pay again") from None

    def verify(self, code_id, identifier, signature=None):
        if signature is not None and len(b58decode(signature)) != 64:
            raise HTTPException(422, "Invalid transaction signature")
        now = int(time.time())
        with self.connection() as db:
            db.execute("BEGIN IMMEDIATE")
            row = db.execute("SELECT * FROM sol_invoices WHERE id=? AND code_id=?", (identifier, code_id)).fetchone()
            if not row:
                raise HTTPException(404, "Invoice not found")
            invoice = dict(row)
            if invoice["signature"]:
                return self.public_invoice(invoice)
            if now - invoice["last_check"] < 10:
                raise HTTPException(429, "Wait ten seconds before checking again")
            db.execute("UPDATE sol_invoices SET last_check=? WHERE id=?", (now, identifier))
        if invoice["network"] != self.config.network or self.rpc("getGenesisHash", []) != GENESIS[invoice["network"]]:
            raise HTTPException(503, "Payment network mismatch; no membership granted")
        if signature is None:
            candidates = self.rpc("getSignaturesForAddress", [invoice["reference"], {"commitment": "finalized", "limit": 5}])
            for candidate in candidates or []:
                if candidate.get("err") is not None or not candidate.get("signature"):
                    continue
                candidate_signature = candidate["signature"]
                candidate_tx = self.rpc("getTransaction", [candidate_signature, {"encoding": "json", "commitment": "finalized", "maxSupportedTransactionVersion": 0}])
                if candidate_tx and valid_transfer(candidate_tx, invoice, candidate_signature):
                    signature = candidate_signature
                    tx = candidate_tx
                    break
            else:
                raise HTTPException(409, "No matching finalized payment found yet. Wait and check again; do not pay again. You can also paste your transaction signature.")
        else:
            tx = self.rpc("getTransaction", [signature, {"encoding": "json", "commitment": "finalized", "maxSupportedTransactionVersion": 0}])
        if not tx:
            raise HTTPException(409, "Payment not finalized yet; wait and check again without paying again")
        if not valid_transfer(tx, invoice, signature):
            with self.connection() as db:
                db.execute("INSERT INTO sol_payment_audit(invoice_id,event,at) VALUES(?,?,?)", (identifier, "verification_rejected", now))
            raise HTTPException(422, "Transaction does not match this invoice; no membership granted")
        with self.connection() as db:
            db.execute("BEGIN IMMEDIATE")
            current = db.execute("SELECT * FROM sol_invoices WHERE id=?", (identifier,)).fetchone()
            if current["signature"]:
                return self.public_invoice(current)
            if db.execute("SELECT 1 FROM sol_invoices WHERE signature=?", (signature,)).fetchone():
                raise PaymentReplayError(409, "This transaction was already credited")
            member = db.execute("SELECT expires FROM sol_memberships WHERE code_id=? AND network=?", (code_id, invoice["network"])).fetchone()
            expires = max(now, member[0] if member else 0) + invoice["days"]*86400
            db.execute("UPDATE sol_invoices SET signature=?,paid_at=? WHERE id=?", (signature, now, identifier))
            db.execute("INSERT OR REPLACE INTO sol_memberships(code_id,expires,credits,runs_daily,network,daily_credits) VALUES(?,?,?,?,?,?)", (code_id, expires, invoice["credits"], invoice["runs_daily"], invoice["network"], invoice["daily_credits"]))
            db.execute("INSERT INTO sol_payment_audit(invoice_id,event,at) VALUES(?,?,?)", (identifier, "finalized_and_granted", now))
            return self.public_invoice(db.execute("SELECT * FROM sol_invoices WHERE id=?", (identifier,)).fetchone())


class VerifyPayment(BaseModel):
    model_config = ConfigDict(extra="forbid")
    signature: str | None = Field(default=None, min_length=64, max_length=88, pattern=r"^[1-9A-HJ-NP-Za-km-z]+$")


class RecoverMembership(BaseModel):
    model_config = ConfigDict(extra="forbid")
    recovery_code: str = Field(min_length=43, max_length=43, pattern=r"^[A-Za-z0-9_-]+$")


def payment_router(payments, subject):
    router = APIRouter(prefix="/api/beta/membership")
    recovery_limiter = FailedAttemptLimiter(10, 300)

    @router.post("/recovery-code")
    def recovery_code(request: Request):
        return {"recovery_code": payments.recovery_code(subject(request))}

    @router.post("/recover")
    def recover(body: RecoverMembership, request: Request, response: Response):
        key = client_key(request)
        allowed, retry_after = recovery_limiter.check(key)
        if not allowed:
            raise HTTPException(429, "Too many recovery attempts. Try later.", headers={"Retry-After": str(retry_after)})
        try:
            code_id = payments.recover(body.recovery_code)
        except HTTPException:
            recovery_limiter.record_failure(key)
            raise
        recovery_limiter.reset(key)
        config = replace(payments.beta, session_ttl_seconds=31_536_000) if code_id.startswith("visitor-") else payments.beta
        response.set_cookie(BETA_COOKIE, issue_session(config, subject=code_id, kind="beta"), max_age=config.session_ttl_seconds, httponly=True, secure=config.cookie_secure, samesite="strict", path="/")
        return {"restored": True}

    @router.get("")
    def status(request: Request):
        code = subject(request)
        c = payments.config
        return {"enabled": c.enabled and payments.beta.enabled, "network": c.network, "membership": payments.membership(code), "pending_invoice": payments.pending_invoice(code), "price_lamports": c.price_lamports, "days": c.days, "credits": c.credits, "runs_daily": c.runs_daily, "daily_credits": c.daily_credits, "daily_usage": payments.daily_usage(code)}

    @router.post("/invoices")
    def create(request: Request):
        return payments.create_invoice(subject(request))

    @router.post("/invoices/{identifier}/verify")
    def verify(identifier: str, body: VerifyPayment, request: Request):
        return payments.verify(subject(request), identifier, body.signature)

    return router
